apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-example
  namespace: eks-example
  labels:
    app: eks-example
  annotations:
    flux.weave.works/automated: "true" # Modify: set to "true"
spec:
  replicas: 1 # Modify: set to 1
  selector:
    matchLabels:
      app: eks-example
  template:
    metadata:
      labels:
        app: eks-example
    spec:
      containers:
      - name: eks-example
        image: 471473268560.dkr.ecr.us-east-1.amazonaws.com/eks-example:00267ffe # Modify: replace with your image URI
        imagePullPolicy: IfNotPresent
        resources:
          requests: 
            memory: "64Mi" # Modify: set to 64Mi
            cpu: "200m" # Modify: set to 200m
          limits:
            memory: "64Mi" # Modify: set to 64Mi
            cpu: "400m"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
